package epaw.lab3.util;

import java.io.BufferedReader;
import java.io.FileReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.*;
import java.util.stream.Collectors;

public class DBManager {

	private static DBManager instance;
	private Connection connection = null;
	private static final String DB_FILE = "lab3.db";

	private DBManager() {
		try {
			Class.forName("org.sqlite.JDBC");
			boolean dbExists = Files.exists(Paths.get(DB_FILE));
			connection = DriverManager.getConnection("jdbc:sqlite:" + DB_FILE);

			try (Statement stmt = connection.createStatement()) {
				stmt.execute("PRAGMA foreign_keys = ON;");
			}

			if (!dbExists) {
				initDatabase();
			} else {
				ensureSchema();
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public static synchronized DBManager getInstance() {
		if (instance == null) {
			instance = new DBManager();
		}
		return instance;
	}

	private void ensureSchema() throws SQLException {
		try (Statement stmt = connection.createStatement()) {
			stmt.execute("""
				CREATE TABLE IF NOT EXISTS GroupJoinRequest (
				    user_id INTEGER NOT NULL,
				    group_id INTEGER NOT NULL,
				    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				    PRIMARY KEY (user_id, group_id),
				    FOREIGN KEY (user_id) REFERENCES User(user_id) ON DELETE CASCADE,
				    FOREIGN KEY (group_id) REFERENCES "Group"(group_id) ON DELETE CASCADE
				)
			""");
			stmt.execute("""
				INSERT INTO UserInGroup (user_id, group_id)
				SELECT u.user_id, g.group_id
				FROM "Group" g
				JOIN User u ON u.username = g.owner
				WHERE g.owner IS NOT NULL
				AND NOT EXISTS (
				    SELECT 1 FROM UserInGroup uig
				    WHERE uig.user_id = u.user_id AND uig.group_id = g.group_id
				)
			""");
			try {
				stmt.execute("ALTER TABLE Post ADD COLUMN blocked INTEGER DEFAULT 0");
			} catch (SQLException ignored) {
				// column already exists
			}
			try {
				stmt.execute("ALTER TABLE Post ADD COLUMN block_reason TEXT");
			} catch (SQLException ignored) {
				// column already exists
			}
			try {
				stmt.execute("ALTER TABLE Post ADD COLUMN author_banned INTEGER DEFAULT 0");
			} catch (SQLException ignored) {
				// column already exists
			}
			try {
				stmt.execute("ALTER TABLE Block ADD COLUMN reason TEXT");
			} catch (SQLException ignored) {
				// column already exists
			}
			try {
				stmt.execute("ALTER TABLE \"Group\" ADD COLUMN blocked INTEGER DEFAULT 0");
			} catch (SQLException ignored) {
				// column already exists
			}
			try {
				stmt.execute("ALTER TABLE \"Group\" ADD COLUMN block_reason TEXT");
			} catch (SQLException ignored) {
				// column already exists
			}
			try {
				stmt.execute("ALTER TABLE Post ADD COLUMN edited INTEGER DEFAULT 0");
			} catch (SQLException ignored) {
				// column already exists
			}
		}
	}

	private void initDatabase() throws Exception {
		String schemaPath = "DB.txt";
		try (BufferedReader reader = new BufferedReader(new FileReader(schemaPath))) {
			String schema = reader.lines().collect(Collectors.joining("\n"));
			String[] statements = schema.split(";");
			try (Statement stmt = connection.createStatement()) {
				for (String sql : statements) {
					if (!sql.trim().isEmpty()) {
						stmt.execute(sql);
					}
				}
			}
		}
	}

	public PreparedStatement prepareStatement(String query) throws SQLException {
		return connection.prepareStatement(query);
	}

	public PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
		return connection.prepareStatement(query, autoGeneratedKeys);
	}

	public void close() {
		try {
			if (connection != null && !connection.isClosed()) {
				connection.close();
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}
